
hexapod:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  base_coxa_joint_1_position_controller:
    type: effort_controllers/JointTrajectoryController
    joint: base_coxa_joint_1
    pid: {p: 10.0, i: 0.0, d: 10}

  coxa_femur_joint_1_position_controller:
    type: effort_controllers/JointTrajectoryController
    joint: coxa_femur_joint_1
    pid: {p: 1000.0, i: 0.0, d: 10}

  femur_tibia_joint_1_position_controller:
    type: effort_controllers/JointTrajectoryController
    joint: femur_tibia_joint_1
    pid: {p: 1000.0, i: 0.0, d: 10}
