
hexapod:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  base_coxa_joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_coxa_joint_1
    pid: {p: 10.0, i: 0.0, d: 1}

  coxa_femur_joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: coxa_femur_joint_1
    pid: {p: 100.0, i: 0.0, d: 1}

  femur_tibia_joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: femur_tibia_joint_1
    pid: {p: 100.0, i: 0.0, d: 1}

  base_coxa_joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_coxa_joint_2
    pid: {p: 10.0, i: 0.0, d: 1}
  
  coxa_femur_joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: coxa_femur_joint_2
    pid: {p: 100.0, i: 0.0, d: 1}

  femur_tibia_joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: femur_tibia_joint_2
    pid: {p: 100.0, i: 0.0, d: 1}

  base_coxa_joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_coxa_joint_3
    pid: {p: 10.0, i: 0.0, d: 1}
  
  coxa_femur_joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: coxa_femur_joint_3
    pid: {p: 100.0, i: 0.0, d: 1}

  femur_tibia_joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: femur_tibia_joint_3
    pid: {p: 100.0, i: 0.0, d: 1}

  base_coxa_joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_coxa_joint_4
    pid: {p: 10.0, i: 0.0, d: 1}
  
  coxa_femur_joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: coxa_femur_joint_4
    pid: {p: 100.0, i: 0.0, d: 1}

  femur_tibia_joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: femur_tibia_joint_4
    pid: {p: 100.0, i: 0.0, d: 1}

  base_coxa_joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_coxa_joint_5
    pid: {p: 10.0, i: 0.0, d: 1}

  coxa_femur_joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: coxa_femur_joint_5
    pid: {p: 100.0, i: 0.0, d: 1}

  femur_tibia_joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: femur_tibia_joint_5
    pid: {p: 100.0, i: 0.0, d: 1}

  base_coxa_joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_coxa_joint_6
    pid: {p: 10.0, i: 0.0, d: 1}

  coxa_femur_joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: coxa_femur_joint_6
    pid: {p: 100.0, i: 0.0, d: 1}

  femur_tibia_joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: femur_tibia_joint_6
    pid: {p: 100.0, i: 0.0, d: 1}